# Generated by Django 4.2 on 2023-11-05 12:46

from django.db import migrations, models
import django.db.models.deletion
import packages.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Perpopulated field bases on package name"
                    ),
                ),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        default="package_image/default.png",
                        upload_to=packages.models.package_fs,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                ("cost_information", models.TextField()),
                ("active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package",
                        to="packages.destination",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TourTimeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stop_name", models.CharField(max_length=250)),
                ("description", models.TextField()),
                (
                    "day",
                    models.PositiveIntegerField(
                        help_text="days count into the trip: int"
                    ),
                ),
                (
                    "tour_timeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_timeline",
                        to="packages.package",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="package",
            name="type",
            field=models.ManyToManyField(blank=True, to="packages.type"),
        ),
    ]
