# Generated by Django 4.2 on 2023-09-29 16:54

from django.db import migrations, models
import django.db.models.deletion
import packages.models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0002_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        default="package_image/default.png",
                        upload_to=packages.models.package_fs,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration", models.PositiveIntegerField()),
                ("cost_information", models.TextField()),
                ("active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package",
                        to="packages.destination",
                    ),
                ),
                ("type", models.ManyToManyField(blank=True, to="packages.type")),
            ],
        ),
    ]
