# Generated by Django 4.2 on 2023-09-29 17:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0003_package"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourTimeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stop_name", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("day", models.PositiveIntegerField()),
                ("order", models.PositiveIntegerField()),
                (
                    "tour_timeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_timeline",
                        to="packages.package",
                    ),
                ),
            ],
        ),
    ]
