# Generated by Django 4.2 on 2023-09-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0004_tourtimeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
