# Generated by Django 4.2 on 2023-10-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0005_package_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
