# Generated by Django 4.2 on 2023-10-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0006_alter_package_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tourtimeline",
            name="order",
        ),
        migrations.AlterField(
            model_name="tourtimeline",
            name="day",
            field=models.PositiveIntegerField(
                help_text="days count into the trip: int"
            ),
        ),
    ]
