# Generated by Django 4.2 on 2023-10-03 16:01

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("firstname", models.CharField(blank=True, max_length=50, null=True)),
                ("lastname", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.profile_image_fs,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "country_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
