# Generated by Django 4.2 on 2023-10-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(default="male", max_length=10),
            preserve_default=False,
        ),
    ]
