# Generated by Django 4.2 on 2023-11-09 16:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
