# Generated by Django 4.2 on 2023-09-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testimonials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="city",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="content",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="country",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="username",
            field=models.CharField(max_length=100),
        ),
    ]
