# Generated by Django 4.2 on 2023-10-06 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("packages", "0007_remove_tourtimeline_order_alter_tourtimeline_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "inquiry_type",
                    models.CharField(
                        choices=[
                            ("destination", "Destination"),
                            ("packages", "Packages"),
                            ("pricing", "Pricing"),
                            ("tickets", "Tickets"),
                        ],
                        default="packages",
                        max_length=25,
                    ),
                ),
                ("inquiry_resolved", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InquiryAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "inquiry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookings.inquiry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kids",
                    models.PositiveIntegerField(
                        default=0, help_text="Age below 12 yrs old"
                    ),
                ),
                (
                    "adults",
                    models.PositiveIntegerField(
                        default=0, help_text="Age above 12 yrs old"
                    ),
                ),
                ("arrival_date", models.DateField()),
                ("arrival_time", models.TimeField()),
                ("airlines", models.CharField(max_length=100)),
                ("flight_number", models.CharField(max_length=50)),
                ("airport_pickup", models.BooleanField(default=True)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("bookings_fullfilled", models.BooleanField(default=False)),
                ("payments_done", models.BooleanField(default=False)),
                ("booked_on", models.DateTimeField(auto_now_add=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_bookings",
                        to="packages.package",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
