# Generated by Django 4.2 on 2023-10-06 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0002_inquiry_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inquiryanswer",
            old_name="answer",
            new_name="content",
        ),
        migrations.AddField(
            model_name="inquiryanswer",
            name="user",
            field=models.ForeignKey(
                default="some content",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiry_replies",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
